name: Maven Tests Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./sae202
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          jacoco-csv-file: ./sae202/target/site/jacoco/jacoco.csv
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coveragebadge
          path: .github/badges/jacoco.svg