name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up working directory
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          working-directory: sae202
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package